---
abstract: 'A Simple Git interface for Padre, the Perl IDE,'
author:
  - 'Kevin Dawson <bowtie@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.98
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Padre::Plugin::Git
name: Padre-Plugin-Git
no_index:
  directory:
    - inc
    - share
    - t
    - xt
requires:
  CPAN::Changes: 0.19
  Carp: 1.26
  Data::Printer: 0.33
  File::Slurp: 9999.19
  File::Spec: 3.33
  File::Which: 1.09
  Padre: 0.96
  Pithub: 0.01016
  Try::Tiny: 0.11
  perl: 5.10.1
  strictures: 1.004004
resources:
  bugtracker: http://padre.perlide.org/trac/wiki/Tickets
  homepage: http://padre.perlide.org/trac/wiki/PadrePluginGit
  license: http://dev.perl.org/licenses/
  repository: http://svn.perlide.org/padre/trunk/Padre-Plugin-Git/
version: 0.09
